version: '3.8'

services:
  selenium:
    image: seleniarm/standalone-firefox:latest
    container_name: selenium
    ports:
      - "4444:4444"
    shm_size: 2gb  # Prevent crashes with large pages

  app:
    build: .
    container_name: app
    depends_on:
      - selenium
      - minio
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MONGO_URI=${MONGO_URI}
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    volumes:
      - .:/app

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  minio_data:
