version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API port
      - "9001:9001"  # MinIO console port
    volumes:
      - minio_data:/data  # Persistent storage for MinIO
    environment:
      MINIO_ROOT_USER: minioadmin  # Default username
      MINIO_ROOT_PASSWORD: minioadmin  # Default password
    command: server /data --console-address ":9001"

volumes:
  minio_data: